# KPI: DEV
# Generated: 2026-08-25T00:04:08.479Z
# Contributed by: Pream-webapps
# Last modified by: devyendarm

KPI Name: DEV

Description: |
  DEV

Category: Conversion


Industry: [[]]












Google Analytics SQL: |
  SELECT user_pseudo_id, user_id, event_name, (SELECT value.string_value FROM UNNEST(event_params) WHERE key = 'item_name') AS item_name, (SELECT value.string_value FROM UNNEST(event_params) WHERE key = 'description') AS description FROM `your_project.your_dataset.your_table` WHERE event_name = 'DEV'

AEP Query Service SQL: |
  SELECT identityMap.ECID[0].id AS mcid, eventType, _experience.analytics.customDimensions.eVars.eVar1 AS item_name, _experience.analytics.customDimensions.eVars.eVar2 AS description FROM your_dataset.your_table WHERE eventType = 'commerce.purchases' AND _experience.analytics.customDimensions.eVars.eVar1 = 'DEV'










Contains PII: No

Status: rejected

Contributed By: Pream-webapps

Created At: 2026-08-25T00:04:06.233+00:00

Last Modified By: devyendarm

Last Modified At: 2026-06-03T21:34:44.834+00:00

