# Dimension: Product Name
# Generated: 2026-03-18T04:51:09.700Z
# Contributed by: devyendarm
# Last modified by: devyendarm

Dimension Name: Product Name
Formula: TRIM(product_name)

Description: |
  A name or title assigned to an individual product SKU (Stock keeping unit) or product offering. It serves as the primary qualitative label used to aggregate performance metrics (like Revenue or Add to cart) across different platforms and reporting suites.

Category: Performance

























Contains PII: No

Status: draft

Contributed By: devyendarm

Created At: 2026-03-18T04:08:15.39+00:00

Last Modified By: devyendarm

Last Modified At: 2026-03-18T04:51:08.345+00:00

