# KPI: DEV
# Generated: 2026-01-13T08:49:55.328Z
# Contributed by: Pream-webapps
# Last modified by: Pream-webapps

KPI Name: DEV

Description: |
  DEV

Category: Conversion


Industry: [[]]






















Contains PII: No

Status: draft

Contributed By: Pream-webapps

Created At: 2026-01-13T08:49:28.295+00:00

Last Modified By: Pream-webapps

Last Modified At: 2026-01-13T08:49:54.257+00:00

